# Generated by Django 3.2.9 on 2021-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizappquestion_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizappquestion',
            name='difficulty',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Easy', 'Easy'), ('Hard', 'Hard')], max_length=100),
        ),
    ]
