# Generated by Django 3.2.9 on 2021-11-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizappquestion_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizappanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizappquestion'),
        ),
        migrations.AlterField(
            model_name='quizappquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard')], max_length=100),
        ),
    ]
