# Generated by Django 3.2.9 on 2021-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211125_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizappquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard'), ('Normal', 'Normal')], max_length=100),
        ),
    ]
