# Generated by Django 3.2.9 on 2021-11-28 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizappquestion_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizappcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='quizappanswer',
            name='anwser_text',
        ),
        migrations.AddField(
            model_name='quizappanswer',
            name='answer_text',
            field=models.CharField(default=datetime.datetime(2021, 11, 28, 17, 19, 13, 147674, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizappanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.quizappquestion'),
        ),
        migrations.AlterField(
            model_name='quizappquestion',
            name='difficulty',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Easy', 'Easy'), ('Hard', 'Hard')], max_length=100),
        ),
        migrations.AlterField(
            model_name='quizappquestion',
            name='title',
            field=models.CharField(max_length=300, verbose_name='question'),
        ),
    ]
