# Generated by Django 3.2.9 on 2021-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20211128_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizapp',
            options={'verbose_name_plural': 'Quizs'},
        ),
        migrations.AlterModelOptions(
            name='quizappanswer',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='quizappquestion',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='quizappquestion',
            name='difficulty',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Hard', 'Hard'), ('Easy', 'Easy')], max_length=100),
        ),
    ]
